/**
 * 知识图谱导出 / 写入工具
 * - 导出 JSON（复用 toGraphDbPayload）
 * - 导出 Cypher（生成可被 Neo4j browser 执行的 MERGE 语句）
 * - 连库时写入 Neo4j（复用 neo4jDataSource.writeKnowledgeGraph）
 */
import { saveAs } from 'file-saver'
import { GRAPH_CODE } from './dataStructureGraph'
import { toGraphDbPayload } from './graphDatabaseAdapter'
import { JSON_PROP_PREFIX, writeKnowledgeGraph } from './neo4jDataSource'

function escapeCypherString(value) {
  if (value == null) return ''
  return String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')
}

function toCypherValue(value) {
  if (value == null) return 'null'
  if (typeof value === 'boolean') return value ? 'true' : 'false'
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'null'
  if (Array.isArray(value)) {
    return `[${value.map(toCypherValue).join(', ')}]`
  }
  if (typeof value === 'object') {
    // 嵌套对象用前缀 + JSON 序列化，与 neo4jDataSource 的 decodeGraphProps 还原保持一致
    return `'${escapeCypherString(JSON_PROP_PREFIX + JSON.stringify(value))}'`
  }
  return `'${escapeCypherString(value)}'`
}

function toCypherMap(obj) {
  const entries = Object.entries(obj || {})
  if (entries.length === 0) return '{}'
  return `{ ${entries.map(([k, v]) => `${k}: ${toCypherValue(v)}`).join(', ')} }`
}

function buildNodeStatements(payload) {
  const graphCode = payload.graphCode || GRAPH_CODE
  return payload.nodes.map((node) => {
    const props = {
      ...(node.properties || {}),
      id: node.id,
      label: node.label,
      type: node.type,
      chapterId: node.chapterId,
      graphCode
    }
    return `MERGE (n:KnowledgeNode { id: '${escapeCypherString(node.id)}', graphCode: '${escapeCypherString(graphCode)}' }) SET n += ${toCypherMap(props)};`
  })
}

function buildRelationStatements(payload) {
  const graphCode = payload.graphCode || GRAPH_CODE
  return payload.relations
    .filter((relation) => relation.source && relation.target && relation.type)
    .map((relation) => {
      const props = { ...(relation.properties || {}) }
      return `MATCH (a:KnowledgeNode { id: '${escapeCypherString(relation.source)}', graphCode: '${escapeCypherString(graphCode)}' }), (b:KnowledgeNode { id: '${escapeCypherString(relation.target)}', graphCode: '${escapeCypherString(graphCode)}' }) MERGE (a)-[r:\`${relation.type}\`]->(b) SET r += ${toCypherMap(props)};`
    })
}

export function buildCypher(graph) {
  const payload = toGraphDbPayload(graph)
  const header = [
    '// Auto-generated by frontend-repo knowledge-graph export',
    `// graphCode: ${payload.graphCode}, version: ${payload.version}`,
    ''
  ]
  return [
    ...header,
    ...buildNodeStatements(payload),
    '',
    ...buildRelationStatements(payload),
    ''
  ].join('\n')
}

export function exportGraphJSON(graph, filename = 'data-structure-graph.json') {
  const payload = toGraphDbPayload(graph)
  const text = JSON.stringify(payload, null, 2)
  saveAs(new Blob([text], { type: 'application/json;charset=utf-8' }), filename)
  return { success: true, mode: 'file', filename }
}

export function exportGraphCypher(graph, filename = 'data-structure-graph.cypher') {
  const text = buildCypher(graph)
  saveAs(new Blob([text], { type: 'text/plain;charset=utf-8' }), filename)
  return { success: true, mode: 'file', filename }
}

export function writeToNeo4j(graph) {
  const payload = toGraphDbPayload(graph)
  return writeKnowledgeGraph(payload)
}
