<template>
  <component :is="ResolvedIcon" :size="size" :stroke-width="strokeWidth" aria-hidden="true" />
</template>

<script setup>
import { computed } from 'vue'
import {
  AlertTriangle,
  ArrowUpRight,
  BarChart3,
  BookOpen,
  Bot,
  Brain,
  Check,
  CheckCircle2,
  Circle,
  CircleX,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  CloudUpload,
  Code2,
  Crosshair,
  FileCode2,
  FileText,
  Flag,
  Flame,
  Folder,
  Globe,
  Hash,
  Inbox,
  LayoutGrid,
  Library,
  Link as LinkIcon,
  ListChecks,
  LoaderCircle,
  Mail,
  Maximize,
  MessageSquare,
  Minimize,
  MousePointerClick,
  Network,
  Package,
  Pause,
  PenLine,
  PieChart,
  Play,
  Plus,
  RefreshCw,
  RotateCw,
  Ruler,
  Scale,
  Search,
  Send,
  Sparkles,
  Square,
  Star,
  Tags,
  Target,
  ThumbsDown,
  ThumbsUp,
  TrendingDown,
  TrendingUp,
  Trash2,
  TreePine,
  TriangleAlert,
  Wrench,
  X,
  ZoomIn,
  ZoomOut
} from 'lucide-vue-next'

const props = defineProps({
  name: {
    type: String,
    required: true
  },
  size: {
    type: [Number, String],
    default: 20
  },
  strokeWidth: {
    type: [Number, String],
    default: 1.8
  }
})

const icons = {
  'alert-triangle': AlertTriangle,
  'arrow-up-right': ArrowUpRight,
  'bar-chart': BarChart3,
  bot: Bot,
  'book-open': BookOpen,
  brain: Brain,
  check: CheckCircle2,
  'check-mark': Check,
  'circle-x': CircleX,
  clock: Clock,
  clipboard: ClipboardList,
  'clipboard-check': ClipboardCheck,
  'clipboard-text': Clipboard,
  'cloud-upload': CloudUpload,
  code: Code2,
  crosshair: Crosshair,
  'file-code': FileCode2,
  file: FileText,
  flag: Flag,
  flame: Flame,
  folder: Folder,
  globe: Globe,
  hash: Hash,
  inbox: Inbox,
  'layout-grid': LayoutGrid,
  library: Library,
  link: LinkIcon,
  'list-checks': ListChecks,
  loader: LoaderCircle,
  mail: Mail,
  maximize: Maximize,
  'message-square': MessageSquare,
  minimize: Minimize,
  'mouse-pointer-click': MousePointerClick,
  network: Network,
  package: Package,
  pause: Pause,
  pen: PenLine,
  'pie-chart': PieChart,
  play: Play,
  plus: Plus,
  refresh: RefreshCw,
  'rotate-cw': RotateCw,
  ruler: Ruler,
  scale: Scale,
  search: Search,
  send: Send,
  sparkles: Sparkles,
  square: Square,
  star: Star,
  tags: Tags,
  target: Target,
  'thumbs-down': ThumbsDown,
  'thumbs-up': ThumbsUp,
  'trend-down': TrendingDown,
  trend: TrendingUp,
  'trash-2': Trash2,
  tree: TreePine,
  'triangle-alert': TriangleAlert,
  wrench: Wrench,
  x: X,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut
}

const ResolvedIcon = computed(() => icons[props.name] || Circle)
</script>
