<template>
  <component :is="ResolvedIcon" :size="size" :stroke-width="strokeWidth" aria-hidden="true" />
</template>

<script setup>
import { computed } from 'vue'
import {
  AlertTriangle,
  ArrowLeft,
  ArrowUpRight,
  BarChart3,
  BookOpen,
  Bookmark,
  Bot,
  Braces,
  Brain,
  Bug,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  Circle,
  CircleX,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  CloudUpload,
  Code2,
  Crosshair,
  Database,
  DatabaseZap,
  Eye,
  EyeOff,
  FileCode2,
  FileText,
  Flag,
  Flame,
  Folder,
  Gauge,
  Globe,
  Hash,
  Image,
  Inbox,
  Layers,
  LayoutGrid,
  Library,
  Lightbulb,
  Link as LinkIcon,
  ListChecks,
  LoaderCircle,
  Mail,
  Maximize,
  MessageSquare,
  Minimize,
  MousePointerClick,
  Network,
  Package,
  Pause,
  PencilRuler,
  PenLine,
  PieChart,
  Play,
  Plus,
  RefreshCw,
  RotateCw,
  RotateCcw,
  Ruler,
  Scale,
  Search,
  Send,
  Sparkles,
  Square,
  Star,
  Tags,
  Target,
  Terminal,
  ThumbsDown,
  ThumbsUp,
  TrendingDown,
  TrendingUp,
  Trash2,
  TreePine,
  TriangleAlert,
  Wrench,
  X,
  ZoomIn,
  ZoomOut
} from 'lucide-vue-next'

const props = defineProps({
  name: {
    type: String,
    required: true
  },
  size: {
    type: [Number, String],
    default: 20
  },
  strokeWidth: {
    type: [Number, String],
    default: 1.8
  }
})

const icons = {
  'alert-triangle': AlertTriangle,
  'arrow-left': ArrowLeft,
  'arrow-up-right': ArrowUpRight,
  'bar-chart': BarChart3,
  bot: Bot,
  'book-open': BookOpen,
  bookmark: Bookmark,
  braces: Braces,
  brain: Brain,
  bug: Bug,
  check: CheckCircle2,
  'circle-check': CheckCircle2,
  'check-mark': Check,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'circle-x': CircleX,
  clock: Clock,
  clipboard: ClipboardList,
  'clipboard-check': ClipboardCheck,
  'clipboard-text': Clipboard,
  'cloud-upload': CloudUpload,
  code: Code2,
  crosshair: Crosshair,
  database: Database,
  'database-zap': DatabaseZap,
  eye: Eye,
  'eye-off': EyeOff,
  'file-code': FileCode2,
  file: FileText,
  flag: Flag,
  flame: Flame,
  folder: Folder,
  gauge: Gauge,
  globe: Globe,
  hash: Hash,
  image: Image,
  inbox: Inbox,
  layers: Layers,
  'layout-grid': LayoutGrid,
  library: Library,
  lightbulb: Lightbulb,
  link: LinkIcon,
  'list-checks': ListChecks,
  loader: LoaderCircle,
  mail: Mail,
  maximize: Maximize,
  'message-square': MessageSquare,
  minimize: Minimize,
  'mouse-pointer-click': MousePointerClick,
  network: Network,
  package: Package,
  pause: Pause,
  pen: PenLine,
  'pencil-ruler': PencilRuler,
  'pie-chart': PieChart,
  play: Play,
  plus: Plus,
  refresh: RefreshCw,
  'rotate-cw': RotateCw,
  'rotate-ccw': RotateCcw,
  ruler: Ruler,
  scale: Scale,
  search: Search,
  send: Send,
  sparkles: Sparkles,
  square: Square,
  star: Star,
  tags: Tags,
  target: Target,
  terminal: Terminal,
  'thumbs-down': ThumbsDown,
  'thumbs-up': ThumbsUp,
  'trend-down': TrendingDown,
  trend: TrendingUp,
  'trash-2': Trash2,
  tree: TreePine,
  'triangle-alert': TriangleAlert,
  wrench: Wrench,
  x: X,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut
}

const ResolvedIcon = computed(() => icons[props.name] || Circle)
</script>
